# Generated by Django 5.2.7 on 2025-11-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_custom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_types',
            field=models.CharField(choices=[('CR', 'Credit'), ('DR', 'Debit')], default='CR', max_length=2),
        ),
    ]
