# Generated by Django 5.2.7 on 2025-11-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_custom', '0002_transaction_transaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_title',
            field=models.CharField(default='Untitled', max_length=50),
        ),
    ]
