# Generated by Django 5.2.7 on 2025-11-13 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_custom', '0003_transaction_transaction_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': [('can_edit_transaction', 'Can Edit Transaction'), ('can_approve_transaction', 'Can approve transaction')]},
        ),
    ]
