# Generated by Django 5.2.7 on 2025-11-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapplications', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrationForm',
            new_name='Registration',
        ),
    ]
