# Generated by Django 5.2.7 on 2025-11-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_types', models.CharField(choices=[('CR', 'Credit'), ('DR', 'Debit')], max_length=2)),
                ('transaction_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
